apiVersion: v1
kind: Pod
metadata:
  name: pod-configmap
spec:
  containers:
  - name: debian
    image: debian:9
    command:
      - sleep
      - "3600"
    envFrom:
      - configMapRef:
          name: bashrc-configmap
