---
- hosts: all
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: Garantindo /etc/hosts
      lineinfile:
        path: /etc/hosts
        line: "{{ item }}"
      with_items:
        - 172.16.0.150 kube-balancer
        - 172.16.0.151 kube-multi-master1
        - 172.16.0.152 kube-multi-master2
        - 172.16.0.153 kube-multi-master3

    - name: Instalando pacotes de dependencias para o curso de Kubernetes
      apt:
        name: ['unzip', 'wget', 'elinks', 'rsync']

    - name: Adicionar usuario suporte
      user:
        name: suporte
        shell: /bin/bash
        password : $1$QbUARykG$p2nthVG8AkDvabKPHwboa1

    - name: Criando o arquivo 98_4linux
      copy:
        src: files/98_4linux
        dest: /etc/sudoers.d
        mode: 0644

    - name: Definir permissao de acesso da HOME do usuario suporte
      file:
        path: /home/suporte
        owner: suporte 
        group: suporte 
        state: directory
        recurse: yes
        mode: 0755

