---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ingress-app
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: app
          servicePort: 8080
    host: app.4labs.example
  tls:
  - hosts:
    - app.4labs.example
    secretName: certificado-app-tls
