---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dev
    ver: "0.5"
  name: pod2
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: dev
    ver: "0.5"
  name: pod3
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: dev
  name: nginx-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: dev 
  type: LoadBalancer
