---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-static
  labels:
    static: pod
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: web
          containerPort: 80
          protocol: TCP
