---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
spec:
  containers:
  - name: pod2
    image: ubuntu
#    command: ["/bin/bash", "-ec", "while :;do echo '.'; sleep 5 ;done"]
#  restartPolicy: Never
